import React, { useState } from 'react';

// Placeholder for onAddTransaction prop
const AddTransactionForm = ({ onAddTransaction }) => {
  const [description, setDescription] = useState('');
  const [amount, setAmount] = useState(''); // Keep as string for input field flexibility
  const [category, setCategory] = useState('');

  const onSubmit = e => {
    e.preventDefault();

    if (!description.trim() || !amount.trim() || !category.trim()) {
      alert('Please add a description, amount, and category');
      return;
    }

    const newTransaction = {
      // _id will be generated by backend, or use uuid for frontend-only temp id
      description,
      amount: +amount, // Convert to number
      category
    };

    onAddTransaction(newTransaction);

    // Clear form
    setDescription('');
    setAmount('');
    setCategory('');
  };

  return (
    <>
      <h3>Add new transaction</h3>
      <form onSubmit={onSubmit}>
        <div className="form-control">
          <label htmlFor="description">Description</label>
          <input 
            type="text" 
            value={description} 
            onChange={(e) => setDescription(e.target.value)} 
            placeholder="Enter description..." 
          />
        </div>
        <div className="form-control">
          <label htmlFor="amount">
            Amount <br />
            (negative - expense, positive - income)
          </label>
          <input 
            type="number" 
            value={amount} 
            onChange={(e) => setAmount(e.target.value)} 
            placeholder="Enter amount..." 
          />
        </div>
        <div className="form-control">
          <label htmlFor="category">Category</label>
          <input 
            type="text" 
            value={category} 
            onChange={(e) => setCategory(e.target.value)} 
            placeholder="Enter category..." 
          />
        </div>
        <button className="btn">Add transaction</button>
      </form>
    </>
  );
}

export default AddTransactionForm;
